package migration

func Migration20240226183804() string {
	return `-- 2024-02-26T18:38:04

CREATE TABLE IF NOT EXISTS account (
		id VARCHAR(36) PRIMARY KEY,
		name TEXT NOT NULL,
		product VARCHAR(36) NOT NULL,
		opened DATETIME NOT NULL,
		closed DATETIME,
		cl INTEGER
);

CREATE TABLE IF NOT EXISTS bank (
	id VARCHAR(36) PRIMARY KEY,
	name TEXT NOT NULL,
	max_account INTEGER NOT NULL,
	max_account_period INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS bonus (
	id VARCHAR(36) PRIMARY KEY,
	type TEXT NOT NULL,
	spend INTEGER NOT NULL,
	bonus INTEGER NOT NULL,
	unit TEXT NOT NULL,
	start DATETIME NOT NULL,
	end DATETIME NOT NULL,
	account VARCHAR(36) NOT NULL,
	FOREIGN KEY (account) REFERENCES account (id)
);

CREATE TABLE IF NOT EXISTS product (
	id VARCHAR(36) PRIMARY KEY,
	name TEXT NOT NULL,
	issuer VARCHAR(36) NOT NULL,
	fee INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS reward (
	id VARCHAR(36) PRIMARY KEY,
	category TEXT NOT NULL,
	unit TEXT NOT NULL,
	reward INTEGER NOT NULL,
	product VARCHAR(36) NOT NULL,
	FOREIGN KEY (product) REFERENCES product (id)
);

CREATE TABLE IF NOT EXISTS tx (
	id VARCHAR(36) PRIMARY KEY,
	timestamp DATETIME NOT NULL,
	amount INTEGER NOT NULL,
	category TEXT NOT NULL,
	description TEXT,
	account VARCHAR(36) NOT NULL,
	FOREIGN KEY (account) REFERENCES account (id)
);
`
}
