app = "churn"

[build]
ignorefile = ".gitignore"

[http_service]
internal_port = 8043
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
timeout = "5s"
grace_period = "15s"
interval = "30s"
method = "GET"
path = "/"
